name = "RewardsPro Theme Extension"
type = "theme"
uid = "a58b9b10-e482-42f9-90d4-885a20081116e17dfcf9"

[[extensions]]
type = "theme"
name = "RewardsPro Theme Extension"
handle = "rewardspro-theme-extension"

[[extensions.targeting]]
target = "section"
module = "./blocks/star_rating.liquid"

[[extensions.targeting]]
target = "body"
module = "./blocks/membership_widget.liquid"

[[extensions.targeting]]
target = "section"
module = "./blocks/points_earning_preview.liquid"

[[extensions.targeting]]
target = "section"
module = "./blocks/rewards_hub_section.liquid"

[[extensions.targeting]]
target = "section"
module = "./blocks/rewards_hub_cta.liquid"

[[extensions.targeting]]
target = "section"
module = "./blocks/raffle_teaser.liquid"

[[extensions.targeting]]
target = "section"
module = "./blocks/mystery_box_teaser.liquid"

[[extensions.targeting]]
target = "section"
module = "./blocks/challenge_teaser.liquid"
