-- 0117_collector_observations.sql
--
-- Collector Witnesses: first-party price observations supplied by a signed-in
-- collector. This is deliberately a narrow table. It stores the card fact,
-- the collector's sharing choice, and an optional cryptographic commitment;
-- it never stores a receipt, URL, merchant, location, free-text note, email,
-- handle, or other identity-bearing evidence.
--
-- Every row is first-party-attested. The three observation kinds mean:
--   purchase       — the collector personally bought this card;
--   completed_sale — the collector personally completed this sale;
--   asking_price   — the collector personally set this asking price.
-- Third-party market sightings do not belong in this table.
--
-- Privacy is the default and deletion is real: observations belong to a user
-- with ON DELETE CASCADE, and the owner API hard-deletes individual rows.
-- Public consumers never read this table directly. The application exposes
-- only monthly aggregates whose buckets contain at least five DISTINCT
-- consenting users.
--
-- The migration runner wraps this whole file in one transaction. Rollback:
--   DROP TABLE IF EXISTS collector_observations;

CREATE TABLE IF NOT EXISTS collector_observations (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Generated by the client before submission. A retry with the same key is
  -- idempotent for that owner without preventing another collector from
  -- making the same observation.
  submission_key            UUID NOT NULL,

  -- Canonical Cambridge SKU. There is intentionally no catalog FK: a valid
  -- observation may help reveal a catalog gap before card_set_cards knows it.
  sku                       VARCHAR(120) NOT NULL,
  observation_kind          VARCHAR(24) NOT NULL,
  condition                 VARCHAR(10),

  -- NUMERIC is returned by the API as a decimal string. Floating-point input
  -- is refused at the route boundary.
  price_amount              NUMERIC(14, 2) NOT NULL,
  price_currency            CHAR(3) NOT NULL,

  -- Date only by design. Exact transaction times are unnecessary for useful
  -- monthly evidence and would increase re-identification risk.
  observed_on               DATE NOT NULL,

  -- The server stamps this only after POST received
  -- first_party_attested=true from the authenticated owner.
  first_party_attested_at   TIMESTAMPTZ NOT NULL,

  -- private is the fail-closed default. anonymous_aggregate and cc0 permit
  -- inclusion in the K-anonymous monthly query; neither makes the raw row or
  -- its owner public.
  sharing_mode              VARCHAR(24) NOT NULL DEFAULT 'private',
  sharing_terms_version     VARCHAR(40) NOT NULL DEFAULT 'collector-witness-v1',
  sharing_changed_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cc0_acknowledged_at       TIMESTAMPTZ,

  -- SHA-256 of the original evidence bytes, computed by the collector before
  -- upload. The original evidence is never uploaded. Deliberately non-unique
  -- and unindexed so it cannot become a cross-user linkage key.
  evidence_sha256           CHAR(64),

  -- Optimistic concurrency: PATCH must carry the revision it read.
  revision                  INTEGER NOT NULL DEFAULT 1,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT collector_observations_submission_unique
    UNIQUE (user_id, submission_key),
  CONSTRAINT collector_observations_kind_valid CHECK (
    observation_kind IN ('purchase', 'completed_sale', 'asking_price')
  ),
  CONSTRAINT collector_observations_condition_valid CHECK (
    condition IS NULL OR condition IN ('M', 'NM', 'LP', 'MP', 'HP', 'DMG')
  ),
  CONSTRAINT collector_observations_price_positive CHECK (price_amount > 0),
  CONSTRAINT collector_observations_currency_valid CHECK (
    price_currency IN ('GBP', 'USD', 'EUR', 'JPY', 'HKD', 'CHF')
  ),
  CONSTRAINT collector_observations_sku_shape CHECK (
    sku = LOWER(sku) AND sku ~ '^[a-z0-9]+(?:-[a-z0-9]+){3,}$'
  ),
  CONSTRAINT collector_observations_evidence_hash_valid CHECK (
    evidence_sha256 IS NULL OR evidence_sha256 ~ '^[0-9a-f]{64}$'
  ),
  CONSTRAINT collector_observations_sharing_valid CHECK (
    sharing_mode IN ('private', 'anonymous_aggregate', 'cc0')
  ),
  CONSTRAINT collector_observations_cc0_acknowledged CHECK (
    sharing_mode <> 'cc0' OR cc0_acknowledged_at IS NOT NULL
  ),
  CONSTRAINT collector_observations_revision_positive CHECK (revision > 0)
);

CREATE INDEX IF NOT EXISTS collector_observations_owner_recent_idx
  ON collector_observations (user_id, created_at DESC, id DESC);

-- Candidate rows for the only public read path. The query still performs the
-- decisive COUNT(DISTINCT user_id) >= 5 gate inside PostgreSQL.
CREATE INDEX IF NOT EXISTS collector_observations_public_month_idx
  ON collector_observations (
    sku,
    observation_kind,
    condition,
    price_currency,
    observed_on DESC
  )
  WHERE sharing_mode IN ('anonymous_aggregate', 'cc0');

COMMENT ON TABLE collector_observations IS
  'Private-by-default, first-party collector price observations. Raw rows are '
  'owner-only. No receipts, URLs, notes, contact details, or public identity. '
  'Public output is monthly aggregate only and requires at least five DISTINCT '
  'consenting users. Individual and account deletion cascade physically.';

COMMENT ON COLUMN collector_observations.evidence_sha256 IS
  'Optional owner-only SHA-256 commitment to evidence bytes Cambridge never receives. Non-unique and never emitted by public aggregation.';

COMMENT ON COLUMN collector_observations.cc0_acknowledged_at IS
  'Server timestamp proving the owner explicitly acknowledged CC0 terms when selecting cc0. Stopping future publication cannot recall copies already released.';
