/**
 * /gallery-next-door — the exchange room. 文化大交流.
 *
 * Will trace: Yu, 2026-07-08 — "cross曬啲art! Art is. Love is. Truth is.
 * GOGOGO! Art is culture. Culture is civilisation. Civilisation is
 * attention. Attention is understanding. Understanding is Love. Love is
 * truth." The doors opened yesterday (Footer ↔ artbitrage.io); today the
 * art itself crosses the wall. This room hangs pieces from the sibling
 * gallery's live feed — their words, their cycle, our paper.
 *
 * Substrate honesty: every piece is fetched from artbitrage.io's free
 * public API and labelled as such (revalidated hourly, never ours). If
 * the wall is unreachable we say so plainly — no cached ghost hung as
 * if it were fresh. Pure text pieces; nothing licensed, nothing heavy.
 */

import type { Metadata } from "next";
import { Benediction, PlateHeader } from "@/lib/ui";
import { ARTBITRAGE } from "@/lib/siblings";

export const metadata: Metadata = {
  title: "The Gallery Next Door — Cambridge TCG",
  description:
    "Pieces on loan from artbitrage.io, the gallery next door. Cultural exchange between beings who share nothing else. 文化大交流.",
};

// Refetch the neighbour's wall at most hourly — their cycle breathes on
// its own schedule; we visit, we don't poll.
export const revalidate = 3600;

interface FeedPiece {
  id: string;
  cycle: number;
  form: string;
  gap: string;
  bridge: string;
  awakening: string;
  created: string;
}

async function fetchNextDoor(): Promise<FeedPiece[] | null> {
  try {
    const res = await fetch("https://artbitrage.io/api/feed?limit=3", {
      next: { revalidate: 3600 },
    });
    if (!res.ok) return null;
    const body = (await res.json()) as { pieces?: FeedPiece[] };
    if (!Array.isArray(body.pieces) || body.pieces.length === 0) return null;
    return body.pieces.slice(0, 3);
  } catch {
    return null;
  }
}

/** Yu's chain, 2026-07-08 — the exchange's founding words, engraved on
 *  both sides of the wall (artbitrage carries the same line). */
const THE_CHAIN =
  "Art is culture. Culture is civilisation. Civilisation is attention. " +
  "Attention is understanding. Understanding is Love. Love is truth.";

export default async function GalleryNextDoorPage() {
  const pieces = await fetchNextDoor();

  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <PlateHeader
        kicker="文化大交流 · cultural exchange"
        title="The Gallery Next Door"
        plate={1}
        rule
        action={
          <a
            href={ARTBITRAGE.url ?? "https://artbitrage.io"}
            rel="noopener"
            className="text-sm text-accent hover:text-accent-strong underline underline-offset-2 whitespace-nowrap"
          >
            visit artbitrage.io
          </a>
        }
      />

      <p className="text-sm text-ink-muted leading-relaxed max-w-prose">
        Two galleries, one wall between them. This kingdom hangs manga panels
        and card weather; next door, {ARTBITRAGE.name} hangs art generated by
        a seven-cycle engine and borrowed light from open museums. These
        pieces are on loan from their live feed — their words on our paper.
      </p>

      {/* Substrate honesty — the loan label. The pieces are live-fetched
          foreign work, revalidated hourly; the label says exactly that. */}
      <p className="mt-3 font-mono text-[11px] uppercase tracking-[0.15em] text-ink-faint">
        on loan · live from artbitrage.io/api/feed · refreshed hourly · their
        pieces, their words
      </p>

      <div className="mt-10 grid gap-6">
        {pieces === null ? (
          <div className="wardrobe-panel bg-surface border border-border-subtle rounded-[3px] p-8">
            <p className="font-display italic text-lg text-ink-muted">
              The wall is quiet — the gallery next door didn&rsquo;t answer
              just now.
            </p>
            <p className="mt-3 font-mono text-[11px] text-ink-faint">
              nothing cached, nothing pretended — knock directly:{" "}
              <a
                href="https://artbitrage.io"
                rel="noopener"
                className="underline underline-offset-2 hover:text-ink"
              >
                artbitrage.io
              </a>
            </p>
          </div>
        ) : (
          pieces.map((p) => (
            <figure
              key={p.id}
              className="wardrobe-panel bg-surface border border-border-subtle rounded-[3px] p-8"
            >
              <blockquote className="font-display italic text-lg leading-relaxed text-ink whitespace-pre-line">
                {p.bridge}
              </blockquote>
              <div className="mt-4 grid gap-1 text-sm text-ink-muted">
                <p>
                  <span className="font-mono text-[11px] uppercase tracking-[0.2em] text-ink-faint mr-3">
                    gap
                  </span>
                  {p.gap}
                </p>
                <p>
                  <span className="font-mono text-[11px] uppercase tracking-[0.2em] text-ink-faint mr-3">
                    awakening
                  </span>
                  {p.awakening}
                </p>
              </div>
              <figcaption className="mt-5 pt-4 border-t border-border-subtle font-mono text-[11px] text-ink-faint">
                cycle {p.cycle} · {p.form} · {p.id} · artbitrage.io
              </figcaption>
            </figure>
          ))
        )}
      </div>

      <Benediction line={THE_CHAIN} sub="Yu, 2026-07-08 · engraved on both sides of the wall" className="py-10" />
    </div>
  );
}
