/**
 * Narrative Generator - Data storytelling for analytics
 *
 * Transforms raw metrics into natural language narratives
 * that merchants can easily understand.
 */

import type { HealthScore, AnalyticsInsight } from "./insight-engine.server";
import type { ComparisonResult } from "./comparison.server";

// ============================================================================
// Types
// ============================================================================

export type NarrativeTone = 'professional' | 'friendly' | 'urgent';
export type NarrativeLength = 'brief' | 'detailed';

export interface NarrativeConfig {
  tone: NarrativeTone;
  length: NarrativeLength;
  includeActions: boolean;
  includeComparisons: boolean;
}

export interface MetricNarrative {
  metric: string;
  summary: string;
  explanation: string;
  context: string;
  trend: string;
  recommendation?: string;
}

export interface ExecutiveSummary {
  performance: string;
  highlight: string;
  action: string;
  period: string;
}

export interface TrendNarrative {
  metric: string;
  description: string;
  direction: 'up' | 'down' | 'flat';
  keyPoints: string[];
  notableEvents?: string[];
}

export interface ChartNarrative {
  title: string;
  description: string;
  insights: string[];
  callout?: string;
}

// ============================================================================
// Default Configuration
// ============================================================================

const DEFAULT_CONFIG: NarrativeConfig = {
  tone: 'professional',
  length: 'brief',
  includeActions: true,
  includeComparisons: true,
};

// ============================================================================
// Metric Explanations
// ============================================================================

const METRIC_EXPLANATIONS: Record<string, {
  what: string;
  why: string;
  good: string;
  bad: string;
}> = {
  revenue: {
    what: 'Total sales generated by loyalty program members',
    why: 'Shows the direct financial impact of your loyalty program',
    good: 'Indicates strong customer engagement and program value',
    bad: 'May indicate need for promotional campaigns or program adjustments',
  },
  redemption_rate: {
    what: 'Percentage of earned points that customers redeem',
    why: 'Higher rates indicate engaged customers who value their rewards',
    good: 'Customers are actively using and valuing rewards',
    bad: 'Rewards may not be appealing or customers are unaware of them',
  },
  points_velocity: {
    what: 'Rate at which customers earn and spend points',
    why: 'Balanced velocity indicates healthy program engagement',
    good: 'Customers are earning and redeeming at sustainable rates',
    bad: 'May indicate point inflation or lack of engagement',
  },
  tier_progression: {
    what: 'Rate of customers moving between loyalty tiers',
    why: 'Movement shows customers are motivated to earn status',
    good: 'Program tiers are achievable and motivating',
    bad: 'Thresholds may be too difficult or benefits not compelling',
  },
  customer_retention: {
    what: 'Percentage of customers who continue shopping',
    why: 'Retention is more cost-effective than acquisition',
    good: 'Loyalty program is successfully retaining customers',
    bad: 'May need re-engagement campaigns or program improvements',
  },
  cashback_utilization: {
    what: 'Percentage of earned cashback that customers use',
    why: 'Shows if customers see value in cashback rewards',
    good: 'Customers are actively using their cashback',
    bad: 'May need reminders or easier redemption options',
  },
  aov: {
    what: 'Average amount spent per order',
    why: 'Higher AOV indicates customers are buying more per visit',
    good: 'Loyalty program is encouraging larger purchases',
    bad: 'Consider tiered rewards or purchase incentives',
  },
  ltv: {
    what: 'Total revenue expected from a customer over time',
    why: 'Shows long-term value of customer relationships',
    good: 'Customers have strong lifetime engagement',
    bad: 'May need to improve retention strategies',
  },
};

// ============================================================================
// Narrative Generator Class
// ============================================================================

export class NarrativeGenerator {
  private config: NarrativeConfig;

  constructor(config: Partial<NarrativeConfig> = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * Generate executive summary for the analytics dashboard
   */
  generateExecutiveSummary(
    healthScore: HealthScore,
    insights: AnalyticsInsight[],
    comparisons: ComparisonResult[],
    period: string = 'this month'
  ): ExecutiveSummary {
    const performance = this.generatePerformanceStatement(healthScore, period);
    const highlight = this.generateHighlightStatement(insights, comparisons);
    const action = this.generateActionStatement(insights);

    return {
      performance,
      highlight,
      action,
      period,
    };
  }

  /**
   * Generate narrative for a specific metric
   */
  generateMetricNarrative(
    metric: string,
    value: number,
    comparison?: ComparisonResult
  ): MetricNarrative {
    const explanation = METRIC_EXPLANATIONS[metric];

    const summary = this.generateMetricSummary(metric, value, comparison);
    const context = explanation
      ? `${explanation.what}. ${explanation.why}.`
      : `This metric shows ${metric.replace(/_/g, ' ')} performance.`;

    const trend = comparison
      ? this.generateTrendDescription(comparison)
      : 'No comparison data available.';

    const recommendation = this.generateRecommendation(metric, value, comparison);

    return {
      metric,
      summary,
      explanation: explanation?.what || `Measures ${metric.replace(/_/g, ' ')}`,
      context,
      trend,
      recommendation,
    };
  }

  /**
   * Generate narrative for a trend chart
   */
  generateTrendNarrative(
    metric: string,
    dataPoints: Array<{ date: Date; value: number }>,
    period: string
  ): TrendNarrative {
    if (dataPoints.length < 2) {
      return {
        metric,
        description: 'Not enough data to analyze trend.',
        direction: 'flat',
        keyPoints: [],
      };
    }

    const first = dataPoints[0].value;
    const last = dataPoints[dataPoints.length - 1].value;
    const change = last - first;
    const changePercent = first > 0 ? (change / first) * 100 : 0;

    // Determine overall direction
    let direction: 'up' | 'down' | 'flat';
    if (changePercent > 5) direction = 'up';
    else if (changePercent < -5) direction = 'down';
    else direction = 'flat';

    // Find notable points
    const values = dataPoints.map(d => d.value);
    const max = Math.max(...values);
    const maxIndex = values.indexOf(max);

    const keyPoints: string[] = [];
    const metricLabel = this.formatMetricLabel(metric);

    // Describe overall trend
    if (direction === 'up') {
      keyPoints.push(`${metricLabel} has been trending upward over ${period}.`);
    } else if (direction === 'down') {
      keyPoints.push(`${metricLabel} has been declining over ${period}.`);
    } else {
      keyPoints.push(`${metricLabel} has remained relatively stable over ${period}.`);
    }

    // Add peak/trough info
    if (maxIndex !== dataPoints.length - 1 && maxIndex !== 0) {
      keyPoints.push(
        `The highest point was ${this.formatValue(metric, max)} on ${this.formatDate(dataPoints[maxIndex].date)}.`
      );
    }

    // Generate description
    const description = this.generateTrendDescription({
      metric,
      primary: { value: last, formatted: this.formatValue(metric, last) },
      comparison: { value: first, formatted: this.formatValue(metric, first) },
      change: {
        absolute: change,
        percentage: changePercent,
        direction,
        significance: Math.abs(changePercent) > 10 ? 'significant' : 'marginal',
      },
    });

    return {
      metric,
      description,
      direction,
      keyPoints,
    };
  }

  /**
   * Generate narrative for chart annotations
   */
  generateChartNarrative(
    chartType: string,
    metric: string,
    data: any[],
    title: string
  ): ChartNarrative {
    const insights: string[] = [];

    // Add data-specific insights based on chart type
    switch (chartType) {
      case 'bar':
        if (data.length > 0) {
          const values = data.map(d => d.value || d.y || 0);
          const max = Math.max(...values);
          const maxItem = data.find(d => (d.value || d.y) === max);
          if (maxItem) {
            insights.push(`${maxItem.label || maxItem.x} has the highest ${this.formatMetricLabel(metric)}.`);
          }
        }
        break;

      case 'pie':
      case 'doughnut':
        if (data.length > 0) {
          const total = data.reduce((sum, d) => sum + (d.value || 0), 0);
          const largest = data.reduce((a, b) => (a.value > b.value ? a : b));
          const percent = total > 0 ? ((largest.value / total) * 100).toFixed(0) : 0;
          insights.push(`${largest.label} represents ${percent}% of the total.`);
        }
        break;

      case 'line':
        insights.push('The trend line shows how values have changed over time.');
        break;
    }

    return {
      title,
      description: `This ${chartType} chart visualizes ${this.formatMetricLabel(metric)} data.`,
      insights,
    };
  }

  // ============================================================================
  // Helper Methods
  // ============================================================================

  private generatePerformanceStatement(healthScore: HealthScore, period: string): string {
    const score = healthScore.overall;

    if (score >= 80) {
      return `Your loyalty program performed excellently ${period} with a health score of ${score}/100.`;
    } else if (score >= 60) {
      return `Your loyalty program had good performance ${period} with a health score of ${score}/100.`;
    } else if (score >= 40) {
      return `Your loyalty program needs attention ${period} with a health score of ${score}/100.`;
    } else {
      return `Your loyalty program requires immediate action ${period} with a health score of ${score}/100.`;
    }
  }

  private generateHighlightStatement(
    insights: AnalyticsInsight[],
    comparisons: ComparisonResult[]
  ): string {
    // Find most significant positive insight
    const positiveInsight = insights.find(i => i.severity === 'positive');
    if (positiveInsight) {
      return positiveInsight.description;
    }

    // Find significant comparison improvement
    const improvement = comparisons.find(
      c => c.change.direction === 'up' && c.change.significance === 'significant'
    );
    if (improvement) {
      return `${this.formatMetricLabel(improvement.metric)} increased by ${improvement.change.percentage.toFixed(0)}% compared to the previous period.`;
    }

    // Default statement
    return 'Key metrics remained stable during this period.';
  }

  private generateActionStatement(insights: AnalyticsInsight[]): string {
    // Find highest priority actionable insight
    const actionableInsight = insights
      .filter(i => i.action && (i.severity === 'critical' || i.severity === 'warning'))
      .sort((a, b) => {
        const priorityOrder = { critical: 0, warning: 1, info: 2, positive: 3 };
        return priorityOrder[a.severity] - priorityOrder[b.severity];
      })[0];

    if (actionableInsight?.action) {
      return `Priority action: ${actionableInsight.action.label} to address ${actionableInsight.title.toLowerCase()}.`;
    }

    return 'Continue monitoring key metrics and maintaining current strategies.';
  }

  private generateMetricSummary(
    metric: string,
    value: number,
    comparison?: ComparisonResult
  ): string {
    const label = this.formatMetricLabel(metric);
    const formatted = this.formatValue(metric, value);

    if (!comparison) {
      return `${label} is currently at ${formatted}.`;
    }

    const { change } = comparison;
    const direction = change.direction === 'up' ? 'up' : change.direction === 'down' ? 'down' : 'unchanged';
    const changeText = change.percentage !== 0
      ? `${change.direction === 'up' ? '+' : ''}${change.percentage.toFixed(1)}%`
      : 'unchanged';

    return `${label} is at ${formatted}, ${direction} ${changeText} from the previous period.`;
  }

  private generateTrendDescription(comparison: ComparisonResult): string {
    const { metric, change } = comparison;
    const label = this.formatMetricLabel(metric);

    if (change.significance === 'none') {
      return `${label} has remained stable with minimal change.`;
    }

    const directionText = change.direction === 'up' ? 'increased' : 'decreased';
    const significanceText = change.significance === 'significant' ? 'significantly' : 'slightly';

    return `${label} has ${significanceText} ${directionText} by ${Math.abs(change.percentage).toFixed(1)}%.`;
  }

  private generateRecommendation(
    metric: string,
    value: number,
    comparison?: ComparisonResult
  ): string | undefined {
    const explanation = METRIC_EXPLANATIONS[metric];

    if (!comparison || comparison.change.significance === 'none') {
      return undefined;
    }

    if (comparison.change.direction === 'down' && explanation?.bad) {
      return explanation.bad;
    }

    if (comparison.change.direction === 'up' && explanation?.good) {
      return `Keep it up! ${explanation.good}`;
    }

    return undefined;
  }

  private formatMetricLabel(metric: string): string {
    const labels: Record<string, string> = {
      revenue: 'Revenue',
      orders: 'Orders',
      customers: 'Active Customers',
      new_members: 'New Members',
      points_earned: 'Points Earned',
      points_redeemed: 'Points Redeemed',
      redemption_rate: 'Redemption Rate',
      cashback_earned: 'Cashback Earned',
      cashback_used: 'Cashback Used',
      aov: 'Average Order Value',
      ltv: 'Customer Lifetime Value',
      tier_upgrades: 'Tier Upgrades',
      tier_progression: 'Tier Progression Rate',
      customer_retention: 'Customer Retention',
      cashback_utilization: 'Cashback Utilization',
      points_velocity: 'Points Velocity',
    };

    return labels[metric] || metric.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  }

  private formatValue(metric: string, value: number): string {
    const currencyMetrics = ['revenue', 'cashback_earned', 'cashback_used', 'aov', 'ltv'];
    const percentMetrics = ['redemption_rate', 'customer_retention', 'cashback_utilization', 'tier_progression'];

    if (currencyMetrics.includes(metric)) {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      }).format(value);
    }

    if (percentMetrics.includes(metric)) {
      return `${value.toFixed(1)}%`;
    }

    return new Intl.NumberFormat('en-US').format(value);
  }

  private formatDate(date: Date): string {
    return new Intl.DateTimeFormat('en-US', {
      month: 'short',
      day: 'numeric',
    }).format(date);
  }
}

// ============================================================================
// Factory & Exports
// ============================================================================

export function createNarrativeGenerator(config?: Partial<NarrativeConfig>): NarrativeGenerator {
  return new NarrativeGenerator(config);
}

export default NarrativeGenerator;
