# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f04b5854fb022d67ba9dd097767b465a"
name = "rewardspro-production"
application_url = "https://modifications-titans-plug-applications.trycloudflare.com"
embedded = true
handle = "rewardspro-production"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_store_credit_account_transactions,read_store_credit_accounts"

[auth]
redirect_urls = ["https://modifications-titans-plug-applications.trycloudflare.com/auth/callback", "https://modifications-titans-plug-applications.trycloudflare.com/auth/shopify/callback", "https://modifications-titans-plug-applications.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
