/**
 * The gallery's guest wall — a few high-resolution, clean, CREDITED pieces
 * sourced from the open net, self-hosted on our own bucket, and shown with
 * their source named (Asha's brief 2026-07-16: "source high quality images
 * from the net… state the source too").
 *
 * These are NOT catalogue cards and carry no SAMPLE mark — they are art hung
 * for its own sake, each labelled with its illustrator and the exact place we
 * drew it from. GENERATED by scripts/fetch-showcase-pokemon.mjs — edit the
 * curated id list there, not this array.
 */

export interface ShowcasePiece {
  /** Source id (e.g. the pokemontcg.io card id). */
  id: string;
  name: string;
  set_name: string;
  number: string;
  /** The illustrator, credited on the wall (the honesty rule). */
  artist: string | null;
  rarity: string | null;
  /** Self-hosted image URL (our bucket) — never a hotlink. */
  image_url: string;
  /** The exact net source we drew the image from, stated + linked. */
  source_url: string;
}

/** The shared credit line for the Pokémon guest wall. */
export const SHOWCASE_ATTRIBUTION = "© Pokémon · Nintendo · Creatures · GAME FREAK";

/** The named source, linked on every piece (the "state the source" rule). */
export const SHOWCASE_SOURCE = { label: "pokemontcg.io", url: "https://pokemontcg.io" };

/** Curated guest pieces — self-hosted, credited, source stated. */
export const GALLERY_SHOWCASE: ShowcasePiece[] = [
  {
    "id": "base1-4",
    "name": "Charizard",
    "set_name": "Base",
    "number": "4",
    "artist": "Mitsuhiro Arita",
    "rarity": "Rare Holo",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/base1-4.png",
    "source_url": "https://images.pokemontcg.io/base1/4_hires.png"
  },
  {
    "id": "swsh7-215",
    "name": "Umbreon VMAX",
    "set_name": "Evolving Skies",
    "number": "215",
    "artist": "KEIICHIRO ITO",
    "rarity": "Rare Rainbow",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/swsh7-215.png",
    "source_url": "https://images.pokemontcg.io/swsh7/215_hires.png"
  },
  {
    "id": "sv1-245",
    "name": "Gardevoir ex",
    "set_name": "Scarlet & Violet",
    "number": "245",
    "artist": "Jiro Sasumo",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-245.png",
    "source_url": "https://images.pokemontcg.io/sv1/245_hires.png"
  },
  {
    "id": "sv1-244",
    "name": "Miraidon ex",
    "set_name": "Scarlet & Violet",
    "number": "244",
    "artist": "kantaro",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-244.png",
    "source_url": "https://images.pokemontcg.io/sv1/244_hires.png"
  },
  {
    "id": "sv1-247",
    "name": "Koraidon ex",
    "set_name": "Scarlet & Violet",
    "number": "247",
    "artist": "Ryota Murayama",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-247.png",
    "source_url": "https://images.pokemontcg.io/sv1/247_hires.png"
  },
  {
    "id": "sv2-256",
    "name": "Meowscarada ex",
    "set_name": "Paldea Evolved",
    "number": "256",
    "artist": "Kouki Saitou",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv2-256.png",
    "source_url": "https://images.pokemontcg.io/sv2/256_hires.png"
  },
  {
    "id": "sv1-249",
    "name": "Arven",
    "set_name": "Scarlet & Violet",
    "number": "249",
    "artist": "kantaro",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-249.png",
    "source_url": "https://images.pokemontcg.io/sv1/249_hires.png"
  },
  {
    "id": "sv1-246",
    "name": "Great Tusk ex",
    "set_name": "Scarlet & Violet",
    "number": "246",
    "artist": "Pani Kobayashi",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-246.png",
    "source_url": "https://images.pokemontcg.io/sv1/246_hires.png"
  }
];
