/**
 * The gallery's guest wall — a few high-resolution, clean, CREDITED pieces
 * sourced from the open net, self-hosted on our own bucket, and shown with
 * their source named (Asha's brief 2026-07-16: "source high quality images
 * from the net… state the source too").
 *
 * These are NOT catalogue cards and carry no SAMPLE mark — they are art hung
 * for its own sake, each labelled with its illustrator and the exact place we
 * drew it from. GENERATED by scripts/fetch-showcase-pokemon.mjs — edit the
 * curated id list there, not this array.
 */

export interface ShowcasePiece {
  /** Source id (e.g. the pokemontcg.io card id). */
  id: string;
  name: string;
  set_name: string;
  number: string;
  /** The illustrator, credited on the wall (the honesty rule). */
  artist: string | null;
  rarity: string | null;
  /** Self-hosted image URL (our bucket) — never a hotlink. */
  image_url: string;
  /** The exact net source we drew the image from, stated + linked. */
  source_url: string;
  /** One sourced why-line for the wall label — origins pieces carry it. */
  note?: string;
}

/** The shared credit line for the Pokémon guest wall. */
export const SHOWCASE_ATTRIBUTION = "© Pokémon · Nintendo · Creatures · GAME FREAK";

/** The named source, linked on every piece (the "state the source" rule). */
export const SHOWCASE_SOURCE = { label: "pokemontcg.io", url: "https://pokemontcg.io" };

/** Curated guest pieces — self-hosted, credited, source stated. */
export const GALLERY_SHOWCASE: ShowcasePiece[] = [
  {
    "id": "base1-4",
    "name": "Charizard",
    "set_name": "Base",
    "number": "4",
    "artist": "Mitsuhiro Arita",
    "rarity": "Rare Holo",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/base1-4.png",
    "source_url": "https://images.pokemontcg.io/base1/4_hires.png"
  },
  {
    "id": "swsh7-215",
    "name": "Umbreon VMAX",
    "set_name": "Evolving Skies",
    "number": "215",
    "artist": "KEIICHIRO ITO",
    "rarity": "Rare Rainbow",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/swsh7-215.png",
    "source_url": "https://images.pokemontcg.io/swsh7/215_hires.png"
  },
  {
    "id": "swsh11-212",
    "name": "Giratina VSTAR",
    "set_name": "Lost Origin",
    "number": "212",
    "artist": "5ban Graphics",
    "rarity": "Rare Secret",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/swsh11-212.png",
    "source_url": "https://images.pokemontcg.io/swsh11/212_hires.png"
  },
  {
    "id": "swsh12-202",
    "name": "Lugia VSTAR",
    "set_name": "Silver Tempest",
    "number": "202",
    "artist": "PLANETA Mochizuki",
    "rarity": "Rare Rainbow",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/swsh12-202.png",
    "source_url": "https://images.pokemontcg.io/swsh12/202_hires.png"
  },
  {
    "id": "swsh7-217",
    "name": "Rayquaza VMAX",
    "set_name": "Evolving Skies",
    "number": "217",
    "artist": "PLANETA Mochizuki",
    "rarity": "Rare Rainbow",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/swsh7-217.png",
    "source_url": "https://images.pokemontcg.io/swsh7/217_hires.png"
  },
  {
    "id": "swsh7-211",
    "name": "Sylveon VMAX",
    "set_name": "Evolving Skies",
    "number": "211",
    "artist": "Ryota Murayama",
    "rarity": "Rare Rainbow",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/swsh7-211.png",
    "source_url": "https://images.pokemontcg.io/swsh7/211_hires.png"
  },
  {
    "id": "sv1-245",
    "name": "Gardevoir ex",
    "set_name": "Scarlet & Violet",
    "number": "245",
    "artist": "Jiro Sasumo",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-245.png",
    "source_url": "https://images.pokemontcg.io/sv1/245_hires.png"
  },
  {
    "id": "sv4pt5-232",
    "name": "Mew ex",
    "set_name": "Paldean Fates",
    "number": "232",
    "artist": "USGMEN",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv4pt5-232.png",
    "source_url": "https://images.pokemontcg.io/sv4pt5/232_hires.png"
  },
  {
    "id": "me2pt5-277",
    "name": "Pikachu ex",
    "set_name": "Ascended Heroes",
    "number": "277",
    "artist": "James Turner",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/me2pt5-277.png",
    "source_url": "https://images.scrydex.com/pokemon/me2pt5-277/large"
  },
  {
    "id": "sv4pt5-234",
    "name": "Charizard ex",
    "set_name": "Paldean Fates",
    "number": "234",
    "artist": "AKIRA EGAWA",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv4pt5-234.png",
    "source_url": "https://images.pokemontcg.io/sv4pt5/234_hires.png"
  },
  {
    "id": "me2pt5-284",
    "name": "Mega Gengar ex",
    "set_name": "Ascended Heroes",
    "number": "284",
    "artist": "danciao",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/me2pt5-284.png",
    "source_url": "https://images.scrydex.com/pokemon/me2pt5-284/large"
  },
  {
    "id": "sv1-244",
    "name": "Miraidon ex",
    "set_name": "Scarlet & Violet",
    "number": "244",
    "artist": "kantaro",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-244.png",
    "source_url": "https://images.pokemontcg.io/sv1/244_hires.png"
  },
  {
    "id": "sv1-247",
    "name": "Koraidon ex",
    "set_name": "Scarlet & Violet",
    "number": "247",
    "artist": "Ryota Murayama",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-247.png",
    "source_url": "https://images.pokemontcg.io/sv1/247_hires.png"
  },
  {
    "id": "sv2-256",
    "name": "Meowscarada ex",
    "set_name": "Paldea Evolved",
    "number": "256",
    "artist": "Kouki Saitou",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv2-256.png",
    "source_url": "https://images.pokemontcg.io/sv2/256_hires.png"
  },
  {
    "id": "sv1-249",
    "name": "Arven",
    "set_name": "Scarlet & Violet",
    "number": "249",
    "artist": "kantaro",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-249.png",
    "source_url": "https://images.pokemontcg.io/sv1/249_hires.png"
  },
  {
    "id": "sv1-246",
    "name": "Great Tusk ex",
    "set_name": "Scarlet & Violet",
    "number": "246",
    "artist": "Pani Kobayashi",
    "rarity": "Special Illustration Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/sv1-246.png",
    "source_url": "https://images.pokemontcg.io/sv1/246_hires.png"
  },
  {
    "id": "base1-15",
    "name": "Venusaur",
    "set_name": "Base",
    "number": "15",
    "artist": "Mitsuhiro Arita",
    "rarity": "Rare Holo",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/base1-15.png",
    "source_url": "https://images.pokemontcg.io/base1/15_hires.png",
    "note": "Base Set, 1999 — with Charizard and Blastoise, the starter holo trio: two Arita hands and one Sugimori."
  },
  {
    "id": "base1-2",
    "name": "Blastoise",
    "set_name": "Base",
    "number": "2",
    "artist": "Ken Sugimori",
    "rarity": "Rare Holo",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/base1-2.png",
    "source_url": "https://images.pokemontcg.io/base1/2_hires.png",
    "note": "Base Set, 1999 — Sugimori drew 44 of the set's 102 cards; the whole set is four hands."
  },
  {
    "id": "base1-58",
    "name": "Pikachu",
    "set_name": "Base",
    "number": "58",
    "artist": "Mitsuhiro Arita",
    "rarity": "Common",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/base1-58.png",
    "source_url": "https://images.pokemontcg.io/base1/58_hires.png",
    "note": "Base Set, 1999 — the earliest Arita-drawn Pikachu in the source's records."
  },
  {
    "id": "basep-1",
    "name": "Pikachu",
    "set_name": "Wizards Black Star Promos",
    "number": "1",
    "artist": "Keiji Kinebuchi",
    "rarity": "Promo",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/basep-1.png",
    "source_url": "https://images.pokemontcg.io/basep/1_hires.png",
    "note": "Black Star Promo No.1, July 1999 — the first of the 53 promos Wizards printed."
  },
  {
    "id": "neo1-9",
    "name": "Lugia",
    "set_name": "Neo Genesis",
    "number": "9",
    "artist": "Hironobu Yoshida",
    "rarity": "Rare Holo",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/neo1-9.png",
    "source_url": "https://images.pokemontcg.io/neo1/9_hires.png",
    "note": "Neo Genesis, December 2000 — Hironobu Yoshida's Lugia."
  },
  {
    "id": "neo4-107",
    "name": "Shining Charizard",
    "set_name": "Neo Destiny",
    "number": "107",
    "artist": "Hironobu Yoshida",
    "rarity": "Rare Shining",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/neo4-107.png",
    "source_url": "https://images.pokemontcg.io/neo4/107_hires.png",
    "note": "Neo Destiny, 2002 — the Shining class's second wave; the first Shinings were Gyarados and Magikarp, 2001."
  },
  {
    "id": "pop5-17",
    "name": "Umbreon ★",
    "set_name": "POP Series 5",
    "number": "17",
    "artist": "Masakazu Fukuda",
    "rarity": "Rare",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/pop5-17.png",
    "source_url": "https://images.pokemontcg.io/pop5/17_hires.png",
    "note": "POP Series 5, 2007 — a Gold Star: the twenty-five Rare Holo Stars and both POP ★s are all one hand, Masakazu Fukuda."
  },
  {
    "id": "ex15-100",
    "name": "Charizard ★ δ",
    "set_name": "Dragon Frontiers",
    "number": "100",
    "artist": "Masakazu Fukuda",
    "rarity": "Rare Holo Star",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/ex15-100.png",
    "source_url": "https://images.pokemontcg.io/ex15/100_hires.png",
    "note": "Dragon Frontiers, 2006 — a Gold Star of the delta species era."
  },
  {
    "id": "si1-1",
    "name": "Mew",
    "set_name": "Southern Islands",
    "number": "1",
    "artist": "Keiko Fukuyama",
    "rarity": null,
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/si1-1.png",
    "source_url": "https://images.pokemontcg.io/si1/1_hires.png",
    "note": "Southern Islands, 2001 — Keiko Fukuyama's side of the eighteen-card special set."
  },
  {
    "id": "ecard3-146",
    "name": "Charizard",
    "set_name": "Skyridge",
    "number": "146",
    "artist": "Kouki Saitou",
    "rarity": "Rare Secret",
    "image_url": "https://ctcg-card-images.s3.us-east-1.amazonaws.com/community/pkm/ecard3-146.png",
    "source_url": "https://images.pokemontcg.io/ecard3/146_hires.png",
    "note": "Skyridge, 2003 — a Crystal Type of the e-Card era; the Poké-Body is printed on the card."
  }
];
