/**
 * build-catalog-snapshot — regenerate the static OPTCG catalog.
 *
 * The deck builder (and any future play surface) reads card data from
 * src/data/optcg-catalog-snapshot.json instead of the retired wholesale
 * data plane (tcg-wholesale RDS decommissioned 2026-06-12). This script
 * rebuilds that file from punk-records — a static, versioned JSON dataset
 * generated by vegapull from the official Bandai cardlist
 * (https://github.com/buhbbl/punk-records, English locale).
 *
 * Run when a new set releases:
 *   pnpm --filter cambridgetcg-storefront catalog:snapshot
 *
 * What it does:
 *   1. Fetches english/index/cards_by_id.json + english/packs.json.
 *   2. Maps to the storefront catalog shape (sku = official card id,
 *      e.g. "OP01-001" / "OP01-001_p1" for alt-art parallels; parallel
 *      rarity carries the kingdom's existing "X/P" compound convention).
 *   3. HEAD-validates every official image URL (en.onepiece-cardgame.com)
 *      with bounded concurrency; unverifiable images become null so the
 *      UI's no-image state renders instead of a broken img.
 *   4. Writes the snapshot with provenance (generated_at + source) —
 *      substrate honesty starts in the data file.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const RAW = "https://raw.githubusercontent.com/buhbbl/punk-records/main/english";
const IMG_BASE = "https://en.onepiece-cardgame.com/images/cardlist/card";
const OUT = join(dirname(fileURLToPath(import.meta.url)), "../src/data/optcg-catalog-snapshot.json");

const RARITY_MAP: Record<string, string> = {
  Common: "C",
  Uncommon: "UC",
  Rare: "R",
  SuperRare: "SR",
  SecretRare: "SEC",
  Leader: "L",
  Special: "SP",
  TreasureRare: "TR",
  Promo: "P",
};

interface PunkCard {
  card_id: string;
  name: string;
  rarity: string;
  category: string;
  pack_id: string;
  cost: number | null;
  power: number | null;
  counter: number | null;
  colors: string[];
  types: string[];
  attributes: string[];
}

interface PunkPack {
  id: string;
  raw_title: string;
  title_parts: { label: string | null; prefix: string | null; title: string };
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  return res.json() as Promise<T>;
}

// vegapull keeps the cardlist's HTML escapes ("Ace &amp; Sabo") — decode
// to plain text so the UI doesn't double-escape them.
function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;|&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(parseInt(n, 10)));
}

// Bounded-concurrency map (same shape as the page-side mapPool).
async function mapPool<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i]);
    }
  });
  await Promise.all(workers);
  return results;
}

async function imageExists(url: string): Promise<boolean> {
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const res = await fetch(url, { method: "HEAD" });
      if (res.ok) return true;
      if (res.status === 404 || res.status === 403) return false;
    } catch { /* retry once */ }
  }
  return false;
}

const cardsById = await fetchJson<Record<string, PunkCard>>(`${RAW}/index/cards_by_id.json`);
const packs = await fetchJson<Record<string, PunkPack>>(`${RAW}/packs.json`);

function packSet(packId: string): { code: string; name: string } {
  const pack = packs[packId];
  const label = pack?.title_parts?.label; // "OP-01", "ST-01", "EB-01", …
  if (label) return { code: label.replace(/-/g, ""), name: pack.title_parts.title };
  return { code: "P", name: pack?.title_parts?.title ?? "Promotional" };
}

const ids = Object.keys(cardsById);
console.log(`punk-records: ${ids.length} english cards`);

console.log("validating official image URLs (HEAD, concurrency 12)…");
let missing = 0;
const entries = await mapPool(ids, 12, async (id) => {
  const c = cardsById[id];
  const parallel = /_p\d+$/.test(id);
  const cardNumber = id.replace(/_p\d+$/, "");
  const base = RARITY_MAP[c.rarity] ?? c.rarity;
  const set = packSet(c.pack_id);
  const imageUrl = `${IMG_BASE}/${id}.png`;
  const hasImage = await imageExists(imageUrl);
  if (!hasImage) missing++;
  return {
    sku: id,
    card_number: cardNumber,
    name: decodeEntities(c.name),
    set_code: set.code,
    set_name: decodeEntities(set.name),
    // Alt-art parallels carry the existing "X/P" compound convention —
    // normalizeRarity() classifies them by base rarity everywhere.
    rarity: parallel ? `${base}/P` : base,
    image_url: hasImage ? imageUrl : null,
    // Fields the wholesale catalog never had — real deck-building data
    // from the official cardlist. Free to surface later (cost curves,
    // color filters) without touching this file again.
    category: c.category,
    cost: c.cost,
    power: c.power,
    counter: c.counter,
    colors: c.colors,
    types: c.types,
  };
});

entries.sort((a, b) => a.sku.localeCompare(b.sku, undefined, { numeric: true }));

const snapshot = {
  generated_at: new Date().toISOString().slice(0, 10),
  source: "punk-records (vegapull scrape of the official Bandai cardlist, english locale)",
  source_url: "https://github.com/buhbbl/punk-records",
  card_count: entries.length,
  cards: entries,
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(snapshot));
console.log(`wrote ${OUT}`);
console.log(`${entries.length} cards · ${missing} without a verifiable image`);
