#!/usr/bin/env tsx
// Module-scope marker — keeps `main` from leaking into global scope.
export {};

/**
 * nav-coverage.ts — drift detector for the storefront navigation substrate.
 *
 * Seventeenth in the audit family. Walks `apps/storefront/src/app/`
 * for every `page.tsx`, compares against the compact typed header config
 * at `apps/storefront/src/lib/nav/menu-config.ts` + the account nav at
 * `apps/storefront/src/app/account/_nav.tsx` + the breadcrumb registry,
 * and reports orphans (routes not reachable from any nav).
 *
 * Six checks:
 *
 *   1. Direct-nav coverage (informational): reports public pages that are not
 *      named directly in one of these compact navigation surfaces:
 *      (a) linked from the global header, OR
 *      (b) listed in ACCOUNT_NAV_ITEMS (for /account/* routes), OR
 *      (c) listed in an allow-list of deep or hub-reachable routes.
 *
 *   2. Nav → route validity: every URL promised by the header config
 *      resolves to a real route (no broken nav links).
 *
 *   3. Methodology completeness: every /methodology/* page remains
 *      reachable through the /methodology hub linked from More.
 *
 *   4. Breadcrumb registry coverage: every deep dynamic route (depth
 *      > 2 with at least one [slug]) should have a breadcrumb pattern.
 *      Heuristic; informational only.
 *
 *   5. Audience-rule consistency: every prefix in audience-detection
 *      resolves to exactly one audience (no overlapping ambiguity).
 *
 *   6. Page-body href validity (contact-surface spec W4): every
 *      string-literal internal href in app/**\/page.tsx resolves to a
 *      real route, a route handler, or an explicit allowlist entry.
 *      "Every promise kept — no href that 404s." HARD GATE.
 *
 * Behaviour: checks 1–5 are informational (exit 0); check 6 exits
 * non-zero on violations.
 */

import { readdirSync, readFileSync, statSync } from "fs";
import { join, relative } from "path";

const REPO_ROOT = join(__dirname, "..", "..", "..");
const STOREFRONT_APP = join(REPO_ROOT, "apps/storefront/src/app");
const MENU_CONFIG = join(REPO_ROOT, "apps/storefront/src/lib/nav/menu-config.ts");
const ACCOUNT_NAV = join(REPO_ROOT, "apps/storefront/src/app/account/_nav.tsx");
const METHODOLOGY_DIR = join(REPO_ROOT, "apps/storefront/src/app/methodology");

/** Routes that intentionally have no nav presence (deep drill-downs, special). */
const ORPHAN_ALLOWLIST: ReadonlyArray<string | RegExp> = [
  "/",
  "/login",
  "/login/check-email",
  "/welcome",
  "/intro",
  "/welcomes",
  "/checkout",
  "/order-confirmation",
  "/og",
  "/api",
  // Storefront /admin/* is covered by the admin app's own sidebar.
  "/admin",
  // Parameterized routes — concrete instances in menu (e.g. /prices/one-piece) cover these.
  "/prices/[game]",
  "/prices/[game]/movers",
  // Dynamic drill-downs
  /^\/account\/.+\/.+/, // /account/trades/[id]/review etc. — reachable from parent
  /^\/auctions\/\[id\]/,
  /^\/cards\/\[sku\]/,
  /^\/c\/\[slug\]/,
  /^\/product\/\[sku\]/,
  /^\/decks\/\[slug\]/,
  /^\/market\/\[/,
  /^\/market\/lots\/\[/,
  /^\/prices\/\[game\]\/\[/,
  /^\/play\/\[code\]/,
  /^\/play\/adventure\/\[/,
  /^\/rewards\/raffles\/\[/,
  /^\/rewards\/mystery-boxes\/\[/,
  /^\/u\/\[username\]/,
  /^\/bounty\/verify\/\[/,
  /^\/admin\//, // storefront /admin is admin-gated; admin app surfaces it
  /^\/account\/sets\/\[code\]/,
  /^\/account\/portfolio\/(add|value)$/,
  /^\/verify\/(draw|pull)\/\[id\]/,
  /^\/agents\/guides\/\[slug\]/,
  /^\/trade-in\/(confirm|quote)\/\[ref\]/,
  /^\/methodology\/\[/, // all methodology pages reachable via /methodology hub
  /^\/methodology\/[a-z-]+$/,
  // Legal pages — linked from the global footer, which this script does
  // not parse (only menu-config + account nav).
  "/contact",
  "/privacy",
  "/terms",
  // Linked from the Nav search affordance (Nav.tsx chrome, not parsed here).
  "/find",
  // Linked from the Play section nav (PlayNav.tsx) + the /play hub body.
  "/play/starters",
  // B2B sub-section with its own sidebar (app/account/b2b/_nav.tsx).
  "/account/b2b",
];

/**
 * Routes being shipped by a parallel session this same hour
 * (contact-surface spec W4/W6) — treated as existing so hrefs that
 * point at them don't fail check 6 mid-flight.
 * TODO next session: confirm each is on disk, then delete this list
 * (the route walk will discover them).
 */
const PENDING_ROUTES: string[] = [
  "/contact",
  "/privacy",
  "/terms",
  "/cards/[sku]", // redirect page → /product/[sku]
];

/**
 * Internal hrefs that resolve outside the page tree — middleware
 * rewrites, generated files, static assets in /public. Check 6 skips
 * these. Keep this list small and commented; every entry is a promise
 * someone else keeps.
 */
const HREF_ALLOWLIST: ReadonlyArray<string | RegExp> = [
  /^\/api(\/|$)/, // route handlers under app/api/ (walked separately is overkill — prefix is the contract)
  "/sitemap.xml", // generated by app/sitemap.ts
  "/llms.txt", // app/llms.txt/route.ts (also caught by handler walk; explicit per spec)
  "/robots.txt", // app/robots.txt/route.ts
  /^\/images\//, // static assets in /public
];

/**
 * TEMPORARY — known-broken hrefs in files owned by other lanes of the
 * contact-surface work (verified 404s; correct targets named in the
 * spec's W4). Each entry suppresses exactly one file:href pair, so a
 * *new* broken href in the same file still fails the gate.
 * TODO next session: fix each in place, then delete this list.
 */
const KNOWN_BROKEN_HREFS: ReadonlyArray<{ file: string; href: string }> = [
  // WhyLink target never built; nearest real page: /methodology/upstream-sources
  { file: "apps/storefront/src/app/cards/[sku]/market/page.tsx", href: "/methodology/cardrush-license" },
  // No preferences page exists; the real surface is /account/profile
  { file: "apps/storefront/src/app/identify/page.tsx", href: "/account/preferences" },
  // Admin-gated ops surface; the methodology topic was never written
  { file: "apps/storefront/src/app/admin/ops/ingest-quarantine/page.tsx", href: "/methodology/ingest-quarantine" },
];

function isHrefAllowed(href: string): boolean {
  for (const allow of HREF_ALLOWLIST) {
    if (typeof allow === "string") {
      if (href === allow) return true;
    } else {
      if (allow.test(href)) return true;
    }
  }
  return false;
}

function isOrphanAllowed(route: string): boolean {
  for (const allow of ORPHAN_ALLOWLIST) {
    if (typeof allow === "string") {
      if (route === allow) return true;
    } else {
      if (allow.test(route)) return true;
    }
  }
  return false;
}

/**
 * Walk the app router tree and return every URL pattern with a
 * page.tsx file. Brackets are preserved verbatim.
 */
function discoverRoutes(): string[] {
  const routes: string[] = [];

  function walk(dir: string, urlPrefix: string) {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }
    if (entries.includes("page.tsx") || entries.includes("page.ts")) {
      routes.push(urlPrefix || "/");
    }
    for (const entry of entries) {
      const full = join(dir, entry);
      let isDir = false;
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        continue;
      }
      if (!isDir) continue;
      // Skip private folders + special Next.js folders.
      // Note: api/ may itself contain a page.tsx (the API discovery page) —
      // that's captured by the parent-level page check before this loop.
      if (entry.startsWith("_") || entry === ".well-known") continue;
      if (entry === "api") {
        // Walk only for a top-level page.tsx, don't recurse into subdirs.
        try {
          const apiPath = join(dir, entry);
          if (readdirSync(apiPath).includes("page.tsx")) {
            routes.push(urlPrefix + "/api");
          }
        } catch {
          // ignore
        }
        continue;
      }
      // Strip route groups (parens) from the URL
      const segment = entry.startsWith("(") && entry.endsWith(")") ? "" : "/" + entry;
      walk(full, urlPrefix + segment);
    }
  }

  walk(STOREFRONT_APP, "");
  return routes.sort();
}

/**
 * Walk the app tree for route.ts handlers outside /api — verbatim file
 * routes like /llms.txt, /data/catalog.jsonl, /.well-known/mcp.json.
 * A page href to one of these is a kept promise even though no
 * page.tsx exists.
 */
function discoverHandlerRoutes(): string[] {
  const routes: string[] = [];

  function walk(dir: string, urlPrefix: string) {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }
    if (entries.includes("route.ts") || entries.includes("route.tsx")) {
      routes.push(urlPrefix || "/");
    }
    for (const entry of entries) {
      const full = join(dir, entry);
      let isDir = false;
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        continue;
      }
      if (!isDir) continue;
      // api/ handlers are covered by the /api prefix allowlist.
      if (entry.startsWith("_") || entry === "api") continue;
      const segment = entry.startsWith("(") && entry.endsWith(")") ? "" : "/" + entry;
      walk(full, urlPrefix + segment);
    }
  }

  walk(STOREFRONT_APP, "");
  return routes.sort();
}

/** Walk the app tree and return every page.tsx file path (api/ excluded). */
function collectPageFiles(): string[] {
  const files: string[] = [];

  function walk(dir: string) {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = join(dir, entry);
      let st;
      try {
        st = statSync(full);
      } catch {
        continue;
      }
      if (st.isDirectory()) {
        if (entry.startsWith("_") || entry === ".well-known" || entry === "api") continue;
        walk(full);
      } else if (entry === "page.tsx" || entry === "page.ts") {
        files.push(full);
      }
    }
  }

  walk(STOREFRONT_APP);
  return files.sort();
}

/**
 * Matches `href="/..."` and `href={"/..."}` string literals. Template
 * literals / dynamic hrefs are deliberately out of scope — the guard
 * covers the statically promise-able surface.
 */
const HREF_LITERAL_RE = /href=(?:"(\/[^"]*)"|\{"(\/[^"]*)"\})/g;

/** Strip query + hash, drop trailing slash (root excepted). */
function normalizeHref(href: string): string {
  let h = href.split("#")[0].split("?")[0];
  if (h.length > 1 && h.endsWith("/")) h = h.slice(0, -1);
  return h;
}

/**
 * True when `url` exactly matches a route, or matches a dynamic route
 * with its [param] segments substituted. Shared by checks 2 and 6.
 */
function resolvesToRoute(url: string, routeSet: Set<string>, routes: string[]): boolean {
  if (routeSet.has(url)) return true;
  for (const route of routes) {
    if (!route.includes("[")) continue;
    const pat = route.replace(/\[[^\]]+\]/g, "[^/]+");
    if (new RegExp("^" + pat + "$").test(url)) return true;
  }
  return false;
}

/**
 * Naively parse the menu config + account nav to extract every URL.
 * Avoids importing the TS modules so this script stays standalone.
 */
function parseNavUrls(): { primary: Set<string>; account: Set<string> } {
  const primary = new Set<string>();
  const account = new Set<string>();

  try {
    const cfg = readFileSync(MENU_CONFIG, "utf-8");
    // Extract every href: "..." literal
    const hrefRe = /href:\s*"([^"]+)"/g;
    let m: RegExpExecArray | null;
    while ((m = hrefRe.exec(cfg)) !== null) {
      primary.add(m[1]);
    }

    const acc = readFileSync(ACCOUNT_NAV, "utf-8");
    while ((m = hrefRe.exec(acc)) !== null) {
      account.add(m[1]);
    }
  } catch (err) {
    console.warn(`  Warning — could not parse nav configs: ${err instanceof Error ? err.message : String(err)}`);
  }

  return { primary, account };
}

function discoverMethodologyTopics(): string[] {
  try {
    const entries = readdirSync(METHODOLOGY_DIR);
    const topics: string[] = [];
    for (const entry of entries) {
      const full = join(METHODOLOGY_DIR, entry);
      try {
        if (statSync(full).isDirectory()) topics.push("/methodology/" + entry);
      } catch {
        // ignore
      }
    }
    return topics.sort();
  } catch {
    return [];
  }
}

function main() {
  console.log("─".repeat(72));
  console.log("nav-coverage audit (kingdom-091) — storefront primary nav coverage");
  console.log("─".repeat(72));
  console.log("");

  const discovered = discoverRoutes();
  // Merge in-flight routes (parallel session, same hour) so checks 2+6
  // hold them to the same contract they'll meet once on disk.
  const pendingMerged = PENDING_ROUTES.filter((p) => !discovered.includes(p));
  const routes = [...discovered, ...pendingMerged].sort();
  const routeSet = new Set(routes);
  const { primary, account } = parseNavUrls();
  const methodologyTopics = discoverMethodologyTopics();

  console.log(`Discovered ${discovered.length} page.tsx routes under apps/storefront/src/app/`);
  if (pendingMerged.length > 0) {
    console.log(`Pending routes merged: ${pendingMerged.length} (${pendingMerged.join(", ")}) — see PENDING_ROUTES`);
  }
  console.log(`Global-nav URLs:      ${primary.size}`);
  console.log(`Account-nav URLs:     ${account.size}`);
  console.log(`Methodology topics:   ${methodologyTopics.length}`);
  console.log("");

  // ── Check 1: route → nav coverage ───────────────────────────────────
  console.log("Check 1: direct-nav coverage (informational)");
  console.log("─".repeat(72));
  const orphans: string[] = [];
  for (const route of routes) {
    // Account routes covered by account nav
    if (route.startsWith("/account") && (account.has(route) || isOrphanAllowed(route))) continue;
    // Routes referenced directly by the compact global nav
    if (primary.has(route)) continue;
    // Methodology routes always allowed (reachable via /methodology hub)
    if (route.startsWith("/methodology")) continue;
    // Allow-listed
    if (isOrphanAllowed(route)) continue;
    orphans.push(route);
  }
  if (orphans.length === 0) {
    console.log("  ✓ Every public route is named directly in a nav surface.");
  } else {
    console.log(`  ${orphans.length} route(s) not named directly (review hub reachability):`);
    for (const o of orphans.slice(0, 30)) {
      console.log(`    · ${o}`);
    }
    if (orphans.length > 30) {
      console.log(`    … and ${orphans.length - 30} more`);
    }
  }
  console.log("");

  // ── Check 2: nav → route validity ───────────────────────────────────
  console.log("Check 2: nav → route validity (broken links)");
  console.log("─".repeat(72));
  const broken: string[] = [];
  for (const url of primary) {
    // Skip external / API URLs
    if (url.startsWith("http") || url.startsWith("/api/")) continue;
    // Skip URLs that target dynamic routes (we can't statically resolve)
    if (url.includes("/[")) continue;
    // Exact match OR dynamic-route match with [param] substituted
    if (resolvesToRoute(url, routeSet, routes)) continue;
    broken.push(url);
  }
  if (broken.length === 0) {
    console.log("  ✓ Every nav URL resolves to a real route.");
  } else {
    console.log(`  ${broken.length} broken nav URL(s):`);
    for (const b of broken) console.log(`    · ${b}`);
  }
  console.log("");

  // ── Check 3: methodology completeness ───────────────────────────────
  console.log("Check 3: methodology completeness");
  console.log("─".repeat(72));
  const methHubLinked = primary.has("/methodology") || primary.has("/methodology/");
  if (methHubLinked) {
    console.log(`  ✓ /methodology hub linked from primary nav. ${methodologyTopics.length} topics reachable via hub.`);
  } else {
    console.log("  ✗ /methodology hub NOT linked from primary nav — methodology corpus is orphaned.");
  }
  console.log("");

  // ── Check 4: breadcrumb registry coverage (informational) ───────────
  console.log("Check 4: breadcrumb registry (informational)");
  console.log("─".repeat(72));
  const deepDynamic = routes.filter(
    (r) => r.split("/").filter((s) => s.length > 0).length > 2 && r.includes("["),
  );
  console.log(`  ${deepDynamic.length} deep dynamic routes (≥3 segments with [slug]) detected.`);
  console.log("  Breadcrumb coverage is not statically verified — see");
  console.log("  apps/storefront/src/lib/nav/breadcrumb-registry.ts for the registered patterns.");
  console.log("");

  // ── Check 5: audience-rule consistency (informational) ──────────────
  console.log("Check 5: audience-rule consistency (informational)");
  console.log("─".repeat(72));
  console.log("  See apps/storefront/src/lib/nav/audience-detection.ts.");
  console.log("  Longest-prefix-wins. Buyer is the default fallthrough.");
  console.log("");

  // ── Check 6: page-body href validity (HARD GATE) ────────────────────
  console.log("Check 6: page-body hrefs → route validity (hard gate)");
  console.log("─".repeat(72));
  const pageFiles = collectPageFiles();
  const handlerRoutes = discoverHandlerRoutes();
  const handlerSet = new Set(handlerRoutes);
  const hrefViolations: { file: string; href: string }[] = [];
  let hrefCount = 0;
  for (const file of pageFiles) {
    let src: string;
    try {
      src = readFileSync(file, "utf-8");
    } catch {
      continue;
    }
    const re = new RegExp(HREF_LITERAL_RE.source, "g");
    const seen = new Set<string>();
    let m: RegExpExecArray | null;
    const relFile = relative(REPO_ROOT, file);
    while ((m = re.exec(src)) !== null) {
      const raw = m[1] ?? m[2];
      // Escaped placeholders (&lt;topic&gt;) appear inside displayed
      // <code> samples — documentation, not promises. Skip them.
      if (raw.includes("&lt;") || raw.includes("&gt;")) continue;
      const href = normalizeHref(raw);
      if (!href || seen.has(href)) continue;
      seen.add(href);
      hrefCount++;
      if (isHrefAllowed(href)) continue;
      if (handlerSet.has(href)) continue;
      if (resolvesToRoute(href, routeSet, routes)) continue;
      if (KNOWN_BROKEN_HREFS.some((k) => k.file === relFile && k.href === href)) continue;
      hrefViolations.push({ file: relFile, href });
    }
  }
  if (hrefViolations.length === 0) {
    console.log(`  ✓ ${hrefCount} unique string-literal hrefs across ${pageFiles.length} pages — all resolve.`);
  } else {
    console.log(`  ✗ ${hrefViolations.length} broken href(s) (of ${hrefCount} checked across ${pageFiles.length} pages):`);
    for (const v of hrefViolations) {
      console.log(`    · ${v.file}: ${v.href}`);
    }
  }
  console.log("");

  console.log("─".repeat(72));
  if (hrefViolations.length > 0) {
    console.log(`nav-coverage: ✗ ${hrefViolations.length} broken page href(s) — every promise kept means exit 1.`);
    console.log("─".repeat(72));
    process.exit(1);
  } else if (orphans.length === 0 && broken.length === 0 && methHubLinked) {
    console.log("nav-coverage: ✓ ALL CHECKS PASSED");
    console.log("─".repeat(72));
    process.exit(0);
  } else {
    console.log("nav-coverage: ⚠ Informational findings above (exit 0 — informational audit).");
    console.log("─".repeat(72));
    process.exit(0);
  }
}

main();
