/** JSON Schema 2020-12 for the roster-free public organisation projection. */

export const COMMUNITY_ORGANISATION_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://cambridgetcg.com/schemas/v1/community-organisation.json",
  title: "Cambridge TCG public community organisation",
  type: "object",
  additionalProperties: false,
  required: [
    "slug",
    "display_name",
    "kind",
    "languages",
    "games",
    "is_public",
    "verification_status",
    "listed_at",
    "created_at",
    "updated_at",
    "profile_url",
    "correction_url",
    "rights",
  ],
  properties: {
    slug: { type: "string", pattern: "^[a-z0-9][a-z0-9-]{1,46}[a-z0-9]$" },
    display_name: { type: "string", minLength: 2, maxLength: 120 },
    kind: {
      type: "string",
      enum: ["shop", "club", "guild", "lab", "tournament-collective", "other"],
    },
    region: { type: ["string", "null"], maxLength: 120 },
    languages: {
      type: "array",
      items: { type: "string", maxLength: 40 },
      maxItems: 20,
      uniqueItems: true,
    },
    games: {
      type: "array",
      items: { type: "string", maxLength: 40 },
      maxItems: 20,
      uniqueItems: true,
    },
    description: { type: ["string", "null"], maxLength: 2000 },
    website_url: {
      type: ["string", "null"],
      format: "uri",
      pattern: "^https://",
      maxLength: 2048,
    },
    public_contact_url: {
      type: ["string", "null"],
      format: "uri",
      pattern: "^https://",
      maxLength: 2048,
    },
    accessibility_notes: { type: ["string", "null"], maxLength: 2000 },
    is_public: { const: true },
    verification_status: { const: "self_attested_unverified" },
    listed_at: { type: "string", format: "date-time" },
    created_at: { type: "string", format: "date-time" },
    updated_at: { type: "string", format: "date-time" },
    profile_url: { type: "string", pattern: "^/c/" },
    correction_url: { type: "string", pattern: "^/contact\\?" },
    rights: {
      type: "object",
      additionalProperties: false,
      required: ["license", "terms_url", "caching", "scope"],
      properties: {
        license: { const: "LicenseRef-CambridgeTCG-Public-Display-Only" },
        terms_url: { const: "/licenses/community-directory-public-display-v1" },
        caching: { const: "no-store" },
        scope: { const: "current-display-only" },
      },
    },
  },
} as const;
